# Generated by Django 5.2.8 on 2026-01-03 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EnhancedInventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("views", models.IntegerField(default=0)),
                ("favorites", models.IntegerField(default=0)),
                ("sales_count", models.IntegerField(default=0)),
                ("listed_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddField(
            model_name="component",
            name="is_discontinued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="component",
            name="reorder_point",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="component",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="etsy_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="margin_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="etsy_listing_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="productcomponent",
            index=models.Index(
                fields=["product"], name="EnhancedInv_product_3e3916_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponent",
            index=models.Index(
                fields=["component"], name="EnhancedInv_compone_1c3e64_idx"
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_data",
                to="EnhancedInventory.product",
            ),
        ),
        migrations.AddIndex(
            model_name="marketsnapshot",
            index=models.Index(
                fields=["product", "recorded_at"], name="EnhancedInv_product_8c79ec_idx"
            ),
        ),
    ]
